export { PostViewModel } from './PostViewModel'
export { PostsViewModelDetail } from './PostsViewModelDetail'
export { CreatePostModel } from './CreatePostModel'
export { UpdatePostModel } from './UpdatePostModel'
export { URIParamsPostModel } from './URIParamsPostModel'